name: Compile LaTeX main file bibliografia.tex
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
 build_and_upload_bibliografia:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        run: |
          lualatex passages
          lualatex bibliografia
          biber bibliografia
          lualatex bibliografia
          lualatex bibliografia
          lualatex bibliografia
          mkdir assets
          cp bibliografia.pdf assets/bibliografia.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bibliografia.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload via ftp the PDF file
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./assets/"
          server-dir: "/httpdocs/home/images/doc/GuideGuIT/"
          security: "strict"
